/* Automatically generated by p4c-ebpf from nikss_ue.p4 on Tue Jul 15 17:07:13 2025
 */
#include "ebpf_kernel.h"

#include <stdbool.h>
#include <linux/if_ether.h>
#include "psa.h"

#define EBPF_MASK(t, w) ((((t)(1)) << (w)) - (t)1)
#define BYTES(w) ((w) / 8)
#define write_partial(a, w, s, v) do { *((u8*)a) = ((*((u8*)a)) & ~(EBPF_MASK(u8, w) << s)) | (v << s) ; } while (0)
#define write_byte(base, offset, v) do { *(u8*)((base) + (offset)) = (v); } while (0)
#define bpf_trace_message(fmt, ...)


#define CLONE_MAX_PORTS 64
#define CLONE_MAX_INSTANCES 1
#define CLONE_MAX_CLONES (CLONE_MAX_PORTS * CLONE_MAX_INSTANCES)
#define CLONE_MAX_SESSIONS 1024

#ifndef PSA_PORT_RECIRCULATE
#define PSA_PORT_RECIRCULATE 0
#endif
#define P4C_PSA_PORT_RECIRCULATE 0xfffffffa

struct internal_metadata {
    __u16 pkt_ether_type;
} __attribute__((aligned(4)));

struct list_key_t {
    __u32 port;
    __u16 instance;
};
typedef struct list_key_t elem_t;

struct element {
    struct clone_session_entry entry;
    elem_t next_id;
} __attribute__((aligned(4)));


struct empty_t {
};
struct ethernet_t {
    u64 dst_mac; /* bit<48> */
    u64 src_mac; /* bit<48> */
    u16 ether_type; /* bit<16> */
    u8 ebpf_valid;
};
struct ipv4_t {
    u8 version; /* bit<4> */
    u8 ihl; /* bit<4> */
    u8 diffserv; /* bit<8> */
    u16 total_len; /* bit<16> */
    u16 identification; /* bit<16> */
    u8 flags; /* bit<3> */
    u16 fragOffset; /* bit<13> */
    u8 ttl; /* bit<8> */
    u8 protocol; /* bit<8> */
    u16 hdr_checksum; /* bit<16> */
    u32 src_ip; /* bit<32> */
    u32 dst_ip; /* bit<32> */
    u8 ebpf_valid;
};
struct d6gmain_t {
    u16 serviceId; /* bit<16> */
    u16 locationId; /* bit<16> */
    u8 hhFlag; /* bit<1> */
    u8 _reserved; /* bit<7> */
    u16 nextNF; /* bit<16> */
    u16 nextHeader; /* bit<16> */
    u8 ebpf_valid;
};
struct d6gint_t {
    u64 t1; /* bit<64> */
    u64 t2; /* bit<64> */
    u64 t3; /* bit<64> */
    u8 ebpf_valid;
};
struct metadata {
};
struct headers {
    struct ethernet_t ethernet; /* ethernet_t */
    struct d6gmain_t d6gmain; /* d6gmain_t */
    struct d6gint_t d6gint; /* d6gint_t */
    struct ipv4_t ipv4; /* ipv4_t */
};
struct ingress_tbl_d6g_fwd_key {
    u16 field0; /* hdr.d6gmain.serviceId */
    u16 field1; /* hdr.d6gmain.nextNF */
    u8 field2; /*     hdr.d6gint.ebpf_valid */
} __attribute__((aligned(4)));
#define INGRESS_TBL_D6G_FWD_ACT_INGRESS_DO_FORWARD 1
#define INGRESS_TBL_D6G_FWD_ACT_INGRESS_DO_FORWARD_T1 2
#define INGRESS_TBL_D6G_FWD_ACT_INGRESS_DO_FORWARD_T2 3
#define INGRESS_TBL_D6G_FWD_ACT_INGRESS_DO_FORWARD_T3 4
struct ingress_tbl_d6g_fwd_value {
    unsigned int action;
    union {
        struct {
        } _NoAction;
        struct {
            u32 egress_port;
        } ingress_do_forward;
        struct {
            u32 egress_port;
        } ingress_do_forward_t1;
        struct {
            u32 egress_port;
        } ingress_do_forward_t2;
        struct {
            u32 egress_port;
        } ingress_do_forward_t3;
    } u;
};
struct ingress_tbl_ipv4_fwd_key {
    u32 prefixlen;
    u32 field0; /* hdr.ipv4.dst_ip */
} __attribute__((aligned(4)));
#define INGRESS_TBL_IPV4_FWD_ACT_INGRESS_DO_FORWARD 1
#define INGRESS_TBL_IPV4_FWD_ACT_INGRESS_DO_ADD_D6G_HEADER 2
struct ingress_tbl_ipv4_fwd_value {
    unsigned int action;
    union {
        struct {
        } _NoAction;
        struct {
            u32 egress_port;
        } ingress_do_forward;
        struct {
            u32 egress_port;
        } ingress_do_add_d6g_header;
    } u;
};

struct lookup_tbl_val {
    u32 table[2048];
};

struct hdr_md {
    struct headers cpumap_hdr;
    struct metadata cpumap_usermeta;
    __u8 __hook;
};

REGISTER_START()
REGISTER_TABLE_INNER(clone_session_tbl_inner, BPF_MAP_TYPE_HASH, elem_t, struct element, 64, 1, 1)
BPF_ANNOTATE_KV_PAIR(clone_session_tbl_inner, elem_t, struct element)
REGISTER_TABLE_OUTER(clone_session_tbl, BPF_MAP_TYPE_ARRAY_OF_MAPS, __u32, __u32, 1024, 1, clone_session_tbl_inner)
BPF_ANNOTATE_KV_PAIR(clone_session_tbl, __u32, __u32)
REGISTER_TABLE_INNER(multicast_grp_tbl_inner, BPF_MAP_TYPE_HASH, elem_t, struct element, 64, 2, 2)
BPF_ANNOTATE_KV_PAIR(multicast_grp_tbl_inner, elem_t, struct element)
REGISTER_TABLE_OUTER(multicast_grp_tbl, BPF_MAP_TYPE_ARRAY_OF_MAPS, __u32, __u32, 1024, 2, multicast_grp_tbl_inner)
BPF_ANNOTATE_KV_PAIR(multicast_grp_tbl, __u32, __u32)
REGISTER_TABLE(ingress_tbl_d6g_fwd, BPF_MAP_TYPE_HASH, struct ingress_tbl_d6g_fwd_key, struct ingress_tbl_d6g_fwd_value, 100)
BPF_ANNOTATE_KV_PAIR(ingress_tbl_d6g_fwd, struct ingress_tbl_d6g_fwd_key, struct ingress_tbl_d6g_fwd_value)
REGISTER_TABLE(ingress_tbl_d6g_fwd_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct ingress_tbl_d6g_fwd_value, 1)
BPF_ANNOTATE_KV_PAIR(ingress_tbl_d6g_fwd_defaultAction, u32, struct ingress_tbl_d6g_fwd_value)
REGISTER_TABLE_FLAGS(ingress_tbl_ipv4_fwd, BPF_MAP_TYPE_LPM_TRIE, struct ingress_tbl_ipv4_fwd_key, struct ingress_tbl_ipv4_fwd_value, 100, BPF_F_NO_PREALLOC)
BPF_ANNOTATE_KV_PAIR(ingress_tbl_ipv4_fwd, struct ingress_tbl_ipv4_fwd_key, struct ingress_tbl_ipv4_fwd_value)
REGISTER_TABLE(ingress_tbl_ipv4_fwd_defaultAction, BPF_MAP_TYPE_ARRAY, u32, struct ingress_tbl_ipv4_fwd_value, 1)
BPF_ANNOTATE_KV_PAIR(ingress_tbl_ipv4_fwd_defaultAction, u32, struct ingress_tbl_ipv4_fwd_value)
REGISTER_TABLE(hdr_md_cpumap, BPF_MAP_TYPE_PERCPU_ARRAY, u32, struct hdr_md, 2)
BPF_ANNOTATE_KV_PAIR(hdr_md_cpumap, u32, struct hdr_md)
REGISTER_TABLE(crc_lookup_tbl, BPF_MAP_TYPE_ARRAY, u32, struct lookup_tbl_val, 1)
BPF_ANNOTATE_KV_PAIR(crc_lookup_tbl, u32, struct lookup_tbl_val)
REGISTER_END()

static __always_inline
void crc16_update(u16 * reg, const u8 * data, u16 data_size, const u16 poly) {
    if (data_size <= 8)
        data += data_size - 1;
    #pragma clang loop unroll(full)
    for (u16 i = 0; i < data_size; i++) {
        bpf_trace_message("CRC16: data byte: %x\n", *data);
        *reg ^= *data;
        for (u8 bit = 0; bit < 8; bit++) {
            *reg = (*reg) & 1 ? ((*reg) >> 1) ^ poly : (*reg) >> 1;
        }
        if (data_size <= 8)
            data--;
        else
            data++;
    }
}
static __always_inline u16 crc16_finalize(u16 reg) {
    return reg;
}
static __always_inline
void crc32_update(u32 * reg, const u8 * data, u16 data_size, const u32 poly) {
    u32* current = (u32*) data;
    struct lookup_tbl_val* lookup_table;
    u32 index = 0;
    lookup_table = BPF_MAP_LOOKUP_ELEM(crc_lookup_tbl, &index);
    u32 lookup_key = 0;
    u32 lookup_value = 0;
    u32 lookup_value1 = 0;
    u32 lookup_value2 = 0;
    u32 lookup_value3 = 0;
    u32 lookup_value4 = 0;
    u32 lookup_value5 = 0;
    u32 lookup_value6 = 0;
    u32 lookup_value7 = 0;
    u32 lookup_value8 = 0;
    u16 tmp = 0;
    if (lookup_table != NULL) {
        for (u16 i = data_size; i >= 8; i -= 8) {
            /* Vars one and two will have swapped byte order if data_size == 8 */
            if (data_size == 8) current = data + 4;
            bpf_trace_message("CRC32: data dword: %x\n", *current);
            u32 one = (data_size == 8 ? __builtin_bswap32(*current--) : *current++) ^ *reg;
            bpf_trace_message("CRC32: data dword: %x\n", *current);
            u32 two = (data_size == 8 ? __builtin_bswap32(*current--) : *current++);
            lookup_key = (one & 0x000000FF);
            lookup_value8 = lookup_table->table[(u16)(1792 + (u8)lookup_key)];
            lookup_key = (one >> 8) & 0x000000FF;
            lookup_value7 = lookup_table->table[(u16)(1536 + (u8)lookup_key)];
            lookup_key = (one >> 16) & 0x000000FF;
            lookup_value6 = lookup_table->table[(u16)(1280 + (u8)lookup_key)];
            lookup_key = one >> 24;
            lookup_value5 = lookup_table->table[(u16)(1024 + (u8)(lookup_key))];
            lookup_key = (two & 0x000000FF);
            lookup_value4 = lookup_table->table[(u16)(768 + (u8)lookup_key)];
            lookup_key = (two >> 8) & 0x000000FF;
            lookup_value3 = lookup_table->table[(u16)(512 + (u8)lookup_key)];
            lookup_key = (two >> 16) & 0x000000FF;
            lookup_value2 = lookup_table->table[(u16)(256 + (u8)lookup_key)];
            lookup_key = two >> 24;
            lookup_value1 = lookup_table->table[(u8)(lookup_key)];
            *reg = lookup_value8 ^ lookup_value7 ^ lookup_value6 ^ lookup_value5 ^
                   lookup_value4 ^ lookup_value3 ^ lookup_value2 ^ lookup_value1;
            tmp += 8;
        }
        volatile int std_algo_lookup_key = 0;
        if (data_size < 8) {
            unsigned char *currentChar = (unsigned char *) current;
            currentChar += data_size - 1;
            for (u16 i = tmp; i < data_size; i++) {
                bpf_trace_message("CRC32: data byte: %x\n", *currentChar);
                std_algo_lookup_key = (u32)(((*reg) & 0xFF) ^ *currentChar--);
                if (std_algo_lookup_key >= 0) {
                    lookup_value = lookup_table->table[(u8)(std_algo_lookup_key & 255)];
                }
                *reg = ((*reg) >> 8) ^ lookup_value;
            }
        } else {
            /* Consume data not processed by slice-by-8 algorithm above, these data are in network byte order */
            unsigned char *currentChar = (unsigned char *) current;
            for (u16 i = tmp; i < data_size; i++) {
                bpf_trace_message("CRC32: data byte: %x\n", *currentChar);
                std_algo_lookup_key = (u32)(((*reg) & 0xFF) ^ *currentChar++);
                if (std_algo_lookup_key >= 0) {
                    lookup_value = lookup_table->table[(u8)(std_algo_lookup_key & 255)];
                }
                *reg = ((*reg) >> 8) ^ lookup_value;
            }
        }
    }
}
static __always_inline u32 crc32_finalize(u32 reg) {
    return reg ^ 0xFFFFFFFF;
}
inline u16 csum16_add(u16 csum, u16 addend) {
    u16 res = csum;
    res += addend;
    return (res + (res < addend));
}
inline u16 csum16_sub(u16 csum, u16 addend) {
    return csum16_add(csum, ~addend);
}
static __always_inline
int do_for_each(SK_BUFF *skb, void *map, unsigned int max_iter, void (*a)(SK_BUFF *, void *))
{
    elem_t head_idx = {0, 0};
    struct element *elem = bpf_map_lookup_elem(map, &head_idx);
    if (!elem) {
        return -1;
    }
    if (elem->next_id.port == 0 && elem->next_id.instance == 0) {
               return 0;
    }
    elem_t next_id = elem->next_id;
    for (unsigned int i = 0; i < max_iter; i++) {
        struct element *elem = bpf_map_lookup_elem(map, &next_id);
        if (!elem) {
            break;
        }
        a(skb, &elem->entry);
        if (elem->next_id.port == 0 && elem->next_id.instance == 0) {
            break;
        }
        next_id = elem->next_id;
    }
    return 0;
}

static __always_inline
void do_clone(SK_BUFF *skb, void *data)
{
    struct clone_session_entry *entry = (struct clone_session_entry *) data;
    bpf_clone_redirect(skb, entry->egress_port, 0);
}

static __always_inline
int do_packet_clones(SK_BUFF * skb, void * map, __u32 session_id, PSA_PacketPath_t new_pkt_path, __u8 caller_id)
{
    struct psa_global_metadata * meta = (struct psa_global_metadata *) skb->cb;
    void * inner_map;
    inner_map = bpf_map_lookup_elem(map, &session_id);
    if (inner_map != NULL) {
        PSA_PacketPath_t original_pkt_path = meta->packet_path;
        meta->packet_path = new_pkt_path;
        if (do_for_each(skb, inner_map, CLONE_MAX_CLONES, &do_clone) < 0) {
            return -1;
        }
        meta->packet_path = original_pkt_path;
    } else {
    }
    return 0;
 }

static __always_inline
void add_prefix_and_entries(__u32 nr_entries,
            __u32 tuple_id,
            void *tuples_map,
            void *prefixes_map,
            void *key_mask,
            void *value_mask,
            void *keysPtrs[],
            void *valuesPtrs[]) {
    int ret = bpf_map_update_elem(prefixes_map, key_mask, value_mask, BPF_ANY);
    if (ret) {
        return;
    }
    if (nr_entries == 0) {
        return;
    }
    struct bpf_elf_map *tuple = bpf_map_lookup_elem(tuples_map, &tuple_id);
    if (tuple) {
        for (__u32 i = 0; i < nr_entries; i++) {
            int ret = bpf_map_update_elem(tuple, keysPtrs[i], valuesPtrs[i], BPF_ANY);
            if (ret) {
                return;
            } else {
            }
        }
    } else {
        return;
    }
}

SEC("classifier/map-initializer")
int map_initializer() {
    u32 ebpf_zero = 0;

    u32 lookup_tbl_key = 0;
    struct lookup_tbl_val* lookup_tbl_value = BPF_MAP_LOOKUP_ELEM(crc_lookup_tbl, &lookup_tbl_key);
    if (lookup_tbl_value != NULL){
        for (u16 i = 0; i <= 255; i++){
            u32 crc = i;
            for (u16 j = 0; j < 8; j++){
                crc = (crc >> 1) ^ ((crc & 1) * 3988292384);
            }
            lookup_tbl_value->table[i] = crc;
        }
        for (u16 i = 0; i <= 255; i++){
            lookup_tbl_value->table[256+i] = (lookup_tbl_value->table[0+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[0+i] & 0xFF)];
            lookup_tbl_value->table[512+i] = (lookup_tbl_value->table[256+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[256+i] & 0xFF)];
            lookup_tbl_value->table[768+i] = (lookup_tbl_value->table[512+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[512+i] & 0xFF)];
            lookup_tbl_value->table[1024+i] = (lookup_tbl_value->table[768+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[768+i] & 0xFF)];
            lookup_tbl_value->table[1280+i] = (lookup_tbl_value->table[1024+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[1024+i] & 0xFF)];
            lookup_tbl_value->table[1536+i] = (lookup_tbl_value->table[1280+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[1280+i] & 0xFF)];
            lookup_tbl_value->table[1792+i] = (lookup_tbl_value->table[1536+i] >> 8) ^ lookup_tbl_value->table[(lookup_tbl_value->table[1536+i] & 0xFF)];
        }
    }
    return 0;
}

SEC("xdp/xdp-ingress")
int xdp_func(struct xdp_md *skb) {
        void *data_end = (void *)(long)skb->data_end;
    struct ethhdr *eth = (struct ethhdr *)(long)skb->data;
    if ((void *)((struct ethhdr *) eth + 1) > data_end) {
        return XDP_ABORTED;
    }
    if (eth->h_proto == bpf_htons(0x0800) || eth->h_proto == bpf_htons(0x86DD)) {
        return XDP_PASS;
    }

    struct internal_metadata *meta;
    int ret = bpf_xdp_adjust_meta(skb, -(int)sizeof(*meta));
    if (ret < 0) {
        return XDP_ABORTED;
    }
    meta = (struct internal_metadata *)(unsigned long)skb->data_meta;
    eth = (void *)(long)skb->data;
    data_end = (void *)(long)skb->data_end;
    if ((void *) ((struct internal_metadata *) meta + 1) > (void *)(long)skb->data)
        return XDP_ABORTED;
    if ((void *)((struct ethhdr *) eth + 1) > data_end) {
        return XDP_ABORTED;
    }
    meta->pkt_ether_type = eth->h_proto;
    eth->h_proto = bpf_htons(0x0800);

    return XDP_PASS;
}
static __always_inline int process(struct __sk_buff *skb, struct headers *parsed_hdr, struct psa_ingress_output_metadata_t *ostd, struct psa_global_metadata *compiler_meta__, struct empty_t *resubmit_meta)
{
    unsigned ebpf_packetOffsetInBits = 0;
    unsigned ebpf_packetOffsetInBits_save = 0;
    ParserError_t ebpf_errorCode = NoError;
    void* pkt = ((void*)(long)skb->data);
    void* ebpf_packetEnd = ((void*)(long)skb->data_end);
    u32 ebpf_zero = 0;
    u32 ebpf_one = 1;
    unsigned char ebpf_byte;
    u32 pkt_len = skb->len;
    u64 tstamp = bpf_ktime_get_ns();
    u32 ebpf_input_port = skb->ifindex;
    if (ebpf_input_port == PSA_PORT_RECIRCULATE) {
        ebpf_input_port = P4C_PSA_PORT_RECIRCULATE;
    }

    struct metadata *meta;
    struct hdr_md *hdrMd;

    hdrMd = BPF_MAP_LOOKUP_ELEM(hdr_md_cpumap, &ebpf_zero);
    if (!hdrMd)
        return TC_ACT_SHOT;
    __builtin_memset(hdrMd, 0, sizeof(struct hdr_md));

    parsed_hdr = &(hdrMd->cpumap_hdr);
    meta = &(hdrMd->cpumap_usermeta);
    {
        struct psa_ingress_parser_input_metadata_t istd = {
            .ingress_port = ebpf_input_port,
            .packet_path = compiler_meta__->packet_path,
        };
        goto start;
        parse_d6gint: {
/* extract(parsed_hdr->d6gint) */
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 192 + 0)) {
                ebpf_errorCode = PacketTooShort;
                goto reject;
            }

            parsed_hdr->d6gint.t1 = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 64;

            parsed_hdr->d6gint.t2 = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 64;

            parsed_hdr->d6gint.t3 = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 64;

            parsed_hdr->d6gint.ebpf_valid = 1;

;
             goto accept;
        }
        parse_d6gmain: {
/* extract(parsed_hdr->d6gmain) */
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 72 + 0)) {
                ebpf_errorCode = PacketTooShort;
                goto reject;
            }

            parsed_hdr->d6gmain.serviceId = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->d6gmain.locationId = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->d6gmain.hhFlag = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 7) & EBPF_MASK(u8, 1));
            ebpf_packetOffsetInBits += 1;

            parsed_hdr->d6gmain._reserved = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u8, 7));
            ebpf_packetOffsetInBits += 7;

            parsed_hdr->d6gmain.nextNF = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->d6gmain.nextHeader = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->d6gmain.ebpf_valid = 1;

;
            u16 select_0;
            select_0 = parsed_hdr->d6gmain.nextHeader;
            if (select_0 == 0xd6d7)goto parse_d6gint;
            if ((select_0 & 0x0) == (0x0 & 0x0))goto accept;
            else goto reject;
        }
        parse_ipv4: {
/* extract(parsed_hdr->ipv4) */
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 160 + 0)) {
                ebpf_errorCode = PacketTooShort;
                goto reject;
            }

            parsed_hdr->ipv4.version = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 4) & EBPF_MASK(u8, 4));
            ebpf_packetOffsetInBits += 4;

            parsed_hdr->ipv4.ihl = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u8, 4));
            ebpf_packetOffsetInBits += 4;

            parsed_hdr->ipv4.diffserv = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ipv4.total_len = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ipv4.identification = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ipv4.flags = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 5) & EBPF_MASK(u8, 3));
            ebpf_packetOffsetInBits += 3;

            parsed_hdr->ipv4.fragOffset = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u16, 13));
            ebpf_packetOffsetInBits += 13;

            parsed_hdr->ipv4.ttl = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ipv4.protocol = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ipv4.hdr_checksum = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ipv4.src_ip = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 32;

            parsed_hdr->ipv4.dst_ip = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 32;

            parsed_hdr->ipv4.ebpf_valid = 1;

;
             goto accept;
        }
        start: {
/* extract(parsed_hdr->ethernet) */
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 112 + 0)) {
                ebpf_errorCode = PacketTooShort;
                goto reject;
            }

            parsed_hdr->ethernet.dst_mac = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits)) >> 16) & EBPF_MASK(u64, 48));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.src_mac = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits)) >> 16) & EBPF_MASK(u64, 48));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.ether_type = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ethernet.ebpf_valid = 1;

;
            u16 select_1;
            select_1 = parsed_hdr->ethernet.ether_type;
            if (select_1 == 0x800)goto parse_ipv4;
            if (select_1 == 0xd6d6)goto parse_d6gmain;
            if ((select_1 & 0x0) == (0x0 & 0x0))goto accept;
            else goto reject;
        }

        reject: {
            if (ebpf_errorCode == 0) {
                return TC_ACT_SHOT;
            }
            goto accept;
        }

    }

    accept: {
        struct psa_ingress_input_metadata_t istd = {
            .ingress_port = ebpf_input_port,
            .packet_path = compiler_meta__->packet_path,
            .parser_error = ebpf_errorCode,
    };
        istd.ingress_timestamp = tstamp;
        u8 hit;
        struct psa_ingress_output_metadata_t *meta_1;
        u32 egress_port_1;
        struct psa_ingress_output_metadata_t *meta_2;
        u32 egress_port_2;
        struct psa_ingress_output_metadata_t *meta_3;
        u32 egress_port_3;
        struct psa_ingress_output_metadata_t *meta_4;
        u32 egress_port_4;
        struct psa_ingress_output_metadata_t *meta_5;
        u32 egress_port_5;
        struct psa_ingress_output_metadata_t *meta_11;
        u32 egress_port_17;
        {
if (/* parsed_hdr->ipv4.isValid() */
            parsed_hdr->ipv4.ebpf_valid) {
/* tbl_ipv4_fwd_0.apply() */
                {
                    /* construct key */
                    struct ingress_tbl_ipv4_fwd_key key = {};
                    key.prefixlen = sizeof(key)*8 - 32;
                    key.field0 = bpf_htonl(parsed_hdr->ipv4.dst_ip);
                    /* value */
                    struct ingress_tbl_ipv4_fwd_value *value = NULL;
                    /* perform lookup */
                    value = BPF_MAP_LOOKUP_ELEM(ingress_tbl_ipv4_fwd, &key);
                    if (value == NULL) {
                        /* miss; find default action */
                        hit = 0;
                        value = BPF_MAP_LOOKUP_ELEM(ingress_tbl_ipv4_fwd_defaultAction, &ebpf_zero);
                    } else {
                        hit = 1;
                    }
                    if (value != NULL) {
                        /* run action */
                        switch (value->action) {
                            case INGRESS_TBL_IPV4_FWD_ACT_INGRESS_DO_FORWARD: 
                                {
                                    meta_5 = ostd;
                                                                        egress_port_5 = value->u.ingress_do_forward.egress_port;
                                                                        meta_5->drop = false;
                                                                        meta_5->multicast_group = 0;
                                                                        meta_5->egress_port = egress_port_5;
                                                                        ostd = meta_5;
                                }
                                break;
                            case INGRESS_TBL_IPV4_FWD_ACT_INGRESS_DO_ADD_D6G_HEADER: 
                                {
                                    meta_11 = ostd;
                                                                        egress_port_17 = value->u.ingress_do_add_d6g_header.egress_port;
                                                                        meta_11->drop = false;
                                                                        meta_11->multicast_group = 0;
                                                                        meta_11->egress_port = egress_port_17;
                                                                        ostd = meta_11;
                                }
                                break;
                            case 0: 
                                {
                                }
                                break;
                            default:
                                return TC_ACT_SHOT;
                        }
                    } else {
                        return TC_ACT_SHOT;
;
                    }
                }
;            }

            else {
if (/* parsed_hdr->d6gmain.isValid() */
                parsed_hdr->d6gmain.ebpf_valid) {
/* tbl_d6g_fwd_0.apply() */
                    {
                        /* construct key */
                        struct ingress_tbl_d6g_fwd_key key = {};
                        key.field0 = parsed_hdr->d6gmain.serviceId;
                        key.field1 = parsed_hdr->d6gmain.nextNF;
                        key.field2 = /* parsed_hdr->d6gint.isValid() */
                        parsed_hdr->d6gint.ebpf_valid;
                        /* value */
                        struct ingress_tbl_d6g_fwd_value *value = NULL;
                        /* perform lookup */
                        value = BPF_MAP_LOOKUP_ELEM(ingress_tbl_d6g_fwd, &key);
                        if (value == NULL) {
                            /* miss; find default action */
                            hit = 0;
                            value = BPF_MAP_LOOKUP_ELEM(ingress_tbl_d6g_fwd_defaultAction, &ebpf_zero);
                        } else {
                            hit = 1;
                        }
                        if (value != NULL) {
                            /* run action */
                            switch (value->action) {
                                case INGRESS_TBL_D6G_FWD_ACT_INGRESS_DO_FORWARD: 
                                    {
                                        meta_4 = ostd;
                                                                                egress_port_4 = value->u.ingress_do_forward.egress_port;
                                                                                meta_4->drop = false;
                                                                                meta_4->multicast_group = 0;
                                                                                meta_4->egress_port = egress_port_4;
                                                                                ostd = meta_4;
                                    }
                                    break;
                                case INGRESS_TBL_D6G_FWD_ACT_INGRESS_DO_FORWARD_T1: 
                                    {
                                        parsed_hdr->d6gint.t1 = (u64)istd.ingress_timestamp;
                                                                                meta_1 = ostd;
                                                                                egress_port_1 = value->u.ingress_do_forward_t1.egress_port;
                                                                                meta_1->drop = false;
                                                                                meta_1->multicast_group = 0;
                                                                                meta_1->egress_port = egress_port_1;
                                                                                ostd = meta_1;
                                    }
                                    break;
                                case INGRESS_TBL_D6G_FWD_ACT_INGRESS_DO_FORWARD_T2: 
                                    {
                                        parsed_hdr->d6gint.t2 = (u64)istd.ingress_timestamp;
                                                                                meta_2 = ostd;
                                                                                egress_port_2 = value->u.ingress_do_forward_t2.egress_port;
                                                                                meta_2->drop = false;
                                                                                meta_2->multicast_group = 0;
                                                                                meta_2->egress_port = egress_port_2;
                                                                                ostd = meta_2;
                                    }
                                    break;
                                case INGRESS_TBL_D6G_FWD_ACT_INGRESS_DO_FORWARD_T3: 
                                    {
                                        parsed_hdr->d6gint.t3 = (u64)istd.ingress_timestamp;
                                                                                meta_3 = ostd;
                                                                                egress_port_3 = value->u.ingress_do_forward_t3.egress_port;
                                                                                meta_3->drop = false;
                                                                                meta_3->multicast_group = 0;
                                                                                meta_3->egress_port = egress_port_3;
                                                                                ostd = meta_3;
                                    }
                                    break;
                                case 0: 
                                    {
                                    }
                                    break;
                                default:
                                    return TC_ACT_SHOT;
                            }
                        } else {
                            return TC_ACT_SHOT;
;
                        }
                    }
;                }
            }

        }
    }
    {
{
;
            ;
        }

        
        if (ostd->clone) {
            do_packet_clones(skb, &clone_session_tbl, ostd->clone_session_id, CLONE_I2E, 1);
        }
        if (ostd->drop) {
            return TC_ACT_SHOT;
        }
        if (ostd->resubmit) {
            compiler_meta__->packet_path = RESUBMIT;
            return TC_ACT_UNSPEC;
        }
        int outHeaderLength = 0;
        if (parsed_hdr->ethernet.ebpf_valid) {
            outHeaderLength += 112;
        }
;        if (parsed_hdr->ipv4.ebpf_valid) {
            outHeaderLength += 160;
        }
;
        int outHeaderOffset = BYTES(outHeaderLength) - BYTES(ebpf_packetOffsetInBits);
        if (outHeaderOffset != 0) {
            int returnCode = 0;
            returnCode = bpf_skb_adjust_room(skb, outHeaderOffset, 1, 0);
            if (returnCode) {
                return TC_ACT_SHOT;
            }
        }
        pkt = ((void*)(long)skb->data);
        ebpf_packetEnd = ((void*)(long)skb->data_end);
        ebpf_packetOffsetInBits = 0;
        if (parsed_hdr->ethernet.ebpf_valid) {
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 112)) {
                return TC_ACT_SHOT;
            }
            
            parsed_hdr->ethernet.dst_mac = htonll(parsed_hdr->ethernet.dst_mac << 16);
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.src_mac = htonll(parsed_hdr->ethernet.src_mac << 16);
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.ether_type = bpf_htons(parsed_hdr->ethernet.ether_type);
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.ether_type))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.ether_type))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

        }
;        if (parsed_hdr->ipv4.ebpf_valid) {
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 160)) {
                return TC_ACT_SHOT;
            }
            
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.version))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 4, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;

            ebpf_byte = ((char*)(&parsed_hdr->ipv4.ihl))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 0, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;

            ebpf_byte = ((char*)(&parsed_hdr->ipv4.diffserv))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ipv4.total_len = bpf_htons(parsed_hdr->ipv4.total_len);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.total_len))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.total_len))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ipv4.identification = bpf_htons(parsed_hdr->ipv4.identification);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.identification))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.identification))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

            ebpf_byte = ((char*)(&parsed_hdr->ipv4.flags))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 3, 5, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 3;

            parsed_hdr->ipv4.fragOffset = bpf_htons(parsed_hdr->ipv4.fragOffset << 3);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.fragOffset))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 5, 0, (ebpf_byte >> 3));
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0 + 1, 3, 5, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.fragOffset))[1];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 1, 5, 0, (ebpf_byte >> 3));
            ebpf_packetOffsetInBits += 13;

            ebpf_byte = ((char*)(&parsed_hdr->ipv4.ttl))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            ebpf_byte = ((char*)(&parsed_hdr->ipv4.protocol))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ipv4.hdr_checksum = bpf_htons(parsed_hdr->ipv4.hdr_checksum);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.hdr_checksum))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.hdr_checksum))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ipv4.src_ip = htonl(parsed_hdr->ipv4.src_ip);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.src_ip))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.src_ip))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.src_ip))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.src_ip))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_packetOffsetInBits += 32;

            parsed_hdr->ipv4.dst_ip = htonl(parsed_hdr->ipv4.dst_ip);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.dst_ip))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.dst_ip))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.dst_ip))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.dst_ip))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_packetOffsetInBits += 32;

        }
;
    }
    return -1;
}
SEC("classifier/tc-ingress")
int tc_ingress_func(struct __sk_buff *skb) {
    struct psa_global_metadata *compiler_meta__ = (struct psa_global_metadata *) skb->cb;
    if (compiler_meta__->pass_to_kernel == true) return TC_ACT_OK;
    if (compiler_meta__->packet_path == NORMAL) {
        compiler_meta__->mark = 153;
        struct internal_metadata *md = (struct internal_metadata *)(unsigned long)skb->data_meta;
        if ((void *) ((struct internal_metadata *) md + 1) <= (void *)(long)skb->data) {
            __u16 *ether_type = (__u16 *) ((void *) (long)skb->data + 12);
            if ((void *) ((__u16 *) ether_type + 1) > (void *) (long) skb->data_end) {
                return TC_ACT_SHOT;
            }
            *ether_type = md->pkt_ether_type;
        }
    }
    struct psa_ingress_output_metadata_t ostd = {
            .drop = true,
    };

    struct empty_t resubmit_meta;
    struct hdr_md *hdrMd;
    struct headers *parsed_hdr;
    int ret = -1;
    #pragma clang loop unroll(disable)
    for (int i = 0; i < 4; i++) {
        ostd.resubmit = 0;
        ret = process(skb, (struct headers *) parsed_hdr, &ostd, compiler_meta__, &resubmit_meta);
        if (ostd.drop == 1 || ostd.resubmit == 0) {
            break;
        }
    }
    if (ret != -1) {
        return ret;
    }
    if (ostd.multicast_group != 0) {
        do_packet_clones(skb, &multicast_grp_tbl, ostd.multicast_group, NORMAL_MULTICAST, 2);
        return TC_ACT_SHOT;
    }
    skb->priority = ostd.class_of_service;
    if (!ostd.drop && ostd.egress_port == 0) {
        compiler_meta__->pass_to_kernel = true;
        return bpf_redirect(skb->ifindex, BPF_F_INGRESS);
    }
    return bpf_redirect(ostd.egress_port, 0);
}

SEC("classifier/tc-egress")
int tc_egress_func(SK_BUFF *skb) {
    struct psa_global_metadata *compiler_meta__ = (struct psa_global_metadata *) skb->cb;
    if (compiler_meta__->mark != 153) {
        return TC_ACT_OK;
    }
    unsigned ebpf_packetOffsetInBits = 0;
    unsigned ebpf_packetOffsetInBits_save = 0;
    ParserError_t ebpf_errorCode = NoError;
    void* pkt = ((void*)(long)skb->data);
    void* ebpf_packetEnd = ((void*)(long)skb->data_end);
    u32 ebpf_zero = 0;
    u32 ebpf_one = 1;
    unsigned char ebpf_byte;
    u32 pkt_len = skb->len;
    u32 ebpf_input_port = skb->ifindex;
    if (ebpf_input_port == PSA_PORT_RECIRCULATE) {
        ebpf_input_port = P4C_PSA_PORT_RECIRCULATE;
    }
    struct metadata *meta;

    struct hdr_md *hdrMd;
    struct headers *parsed_hdr;
    hdrMd = BPF_MAP_LOOKUP_ELEM(hdr_md_cpumap, &ebpf_one);
    if (!hdrMd)
        return TC_ACT_SHOT;
    __builtin_memset(hdrMd, 0, sizeof(struct hdr_md));

    parsed_hdr = &(hdrMd->cpumap_hdr);
    meta = &(hdrMd->cpumap_usermeta);
    struct psa_egress_output_metadata_t ostd = {
       .clone = false,
            .drop = false,
        };

    struct psa_egress_input_metadata_t istd = {
            .class_of_service = skb->priority,
            .egress_port = ebpf_input_port,
            .packet_path = compiler_meta__->packet_path,
            .instance = compiler_meta__->instance,
            .parser_error = ebpf_errorCode,
        };
    {
        struct psa_egress_parser_input_metadata_t istd = {
            .egress_port = ebpf_input_port,
            .packet_path = compiler_meta__->packet_path,
        };
        goto start;
        parse_ipv4: {
/* extract(parsed_hdr->ipv4) */
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 160 + 0)) {
                ebpf_errorCode = PacketTooShort;
                goto reject;
            }

            parsed_hdr->ipv4.version = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 4) & EBPF_MASK(u8, 4));
            ebpf_packetOffsetInBits += 4;

            parsed_hdr->ipv4.ihl = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u8, 4));
            ebpf_packetOffsetInBits += 4;

            parsed_hdr->ipv4.diffserv = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ipv4.total_len = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ipv4.identification = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ipv4.flags = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 5) & EBPF_MASK(u8, 3));
            ebpf_packetOffsetInBits += 3;

            parsed_hdr->ipv4.fragOffset = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u16, 13));
            ebpf_packetOffsetInBits += 13;

            parsed_hdr->ipv4.ttl = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ipv4.protocol = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ipv4.hdr_checksum = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ipv4.src_ip = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 32;

            parsed_hdr->ipv4.dst_ip = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 32;

            parsed_hdr->ipv4.ebpf_valid = 1;

;
             goto accept;
        }
        start: {
/* extract(parsed_hdr->ethernet) */
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 112 + 0)) {
                ebpf_errorCode = PacketTooShort;
                goto reject;
            }

            parsed_hdr->ethernet.dst_mac = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits)) >> 16) & EBPF_MASK(u64, 48));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.src_mac = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits)) >> 16) & EBPF_MASK(u64, 48));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.ether_type = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ethernet.ebpf_valid = 1;

;
            u16 select_2;
            select_2 = parsed_hdr->ethernet.ether_type;
            if (select_2 == 0x800)goto parse_ipv4;
            if ((select_2 & 0x0) == (0x0 & 0x0))goto accept;
            else goto reject;
        }

        reject: {
            if (ebpf_errorCode == 0) {
                return TC_ACT_SHOT;
            }
            goto accept;
        }

    }
    accept:
    istd.parser_error = ebpf_errorCode;

    {

        u8 hit_0;
        {
        }
    }
    {
{
;
            ;
        }

        int outHeaderLength = 0;
        if (parsed_hdr->ethernet.ebpf_valid) {
            outHeaderLength += 112;
        }
;        if (parsed_hdr->ipv4.ebpf_valid) {
            outHeaderLength += 160;
        }
;
        int outHeaderOffset = BYTES(outHeaderLength) - BYTES(ebpf_packetOffsetInBits);
        if (outHeaderOffset != 0) {
            int returnCode = 0;
            returnCode = bpf_skb_adjust_room(skb, outHeaderOffset, 1, 0);
            if (returnCode) {
                return TC_ACT_SHOT;
            }
        }
        pkt = ((void*)(long)skb->data);
        ebpf_packetEnd = ((void*)(long)skb->data_end);
        ebpf_packetOffsetInBits = 0;
        if (parsed_hdr->ethernet.ebpf_valid) {
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 112)) {
                return TC_ACT_SHOT;
            }
            
            parsed_hdr->ethernet.dst_mac = htonll(parsed_hdr->ethernet.dst_mac << 16);
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.dst_mac))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.src_mac = htonll(parsed_hdr->ethernet.src_mac << 16);
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.src_mac))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_packetOffsetInBits += 48;

            parsed_hdr->ethernet.ether_type = bpf_htons(parsed_hdr->ethernet.ether_type);
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.ether_type))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ethernet.ether_type))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

        }
;        if (parsed_hdr->ipv4.ebpf_valid) {
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 160)) {
                return TC_ACT_SHOT;
            }
            
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.version))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 4, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;

            ebpf_byte = ((char*)(&parsed_hdr->ipv4.ihl))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 0, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;

            ebpf_byte = ((char*)(&parsed_hdr->ipv4.diffserv))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ipv4.total_len = bpf_htons(parsed_hdr->ipv4.total_len);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.total_len))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.total_len))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ipv4.identification = bpf_htons(parsed_hdr->ipv4.identification);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.identification))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.identification))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

            ebpf_byte = ((char*)(&parsed_hdr->ipv4.flags))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 3, 5, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 3;

            parsed_hdr->ipv4.fragOffset = bpf_htons(parsed_hdr->ipv4.fragOffset << 3);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.fragOffset))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 5, 0, (ebpf_byte >> 3));
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0 + 1, 3, 5, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.fragOffset))[1];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 1, 5, 0, (ebpf_byte >> 3));
            ebpf_packetOffsetInBits += 13;

            ebpf_byte = ((char*)(&parsed_hdr->ipv4.ttl))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            ebpf_byte = ((char*)(&parsed_hdr->ipv4.protocol))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;

            parsed_hdr->ipv4.hdr_checksum = bpf_htons(parsed_hdr->ipv4.hdr_checksum);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.hdr_checksum))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.hdr_checksum))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;

            parsed_hdr->ipv4.src_ip = htonl(parsed_hdr->ipv4.src_ip);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.src_ip))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.src_ip))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.src_ip))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.src_ip))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_packetOffsetInBits += 32;

            parsed_hdr->ipv4.dst_ip = htonl(parsed_hdr->ipv4.dst_ip);
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.dst_ip))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.dst_ip))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.dst_ip))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr->ipv4.dst_ip))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_packetOffsetInBits += 32;

        }
;
    }
    if (ostd.clone) {
        do_packet_clones(skb, &clone_session_tbl, ostd.clone_session_id, CLONE_E2E, 3);
    }

    if (ostd.drop) {
        return TC_ACT_SHOT;;
    }

    if (istd.egress_port == P4C_PSA_PORT_RECIRCULATE) {
        compiler_meta__->packet_path = RECIRCULATE;
        return bpf_redirect(PSA_PORT_RECIRCULATE, BPF_F_INGRESS);
    }

    
    return TC_ACT_OK;
}
char _license[] SEC("license") = "GPL";
